### ISSUE TITLE
Evaluate need for BasicAuthentiation

### ISSUE THREAD

**Issue by johnbaldwin** [appsembler/figures#86]
Is there a compelling use case for keeping BasicAuthentication? What's the risk of leaving it in there?

**Comment by frob** [comment]
We have run into issues with BasicAuthentication and OAuth. Unless we login with local users (non-oauth) we get a BasicAuthentication popup on some resources within `/figures`. It is odd because the page loads fine, but some/all api calls are requiring additional basic authentication but not `/figures` itself. 

For now we are running `0.3.2` and have commented out the `BasicAuthentication` classes in `figures/views.py`.

**Comment by johnbaldwin** [comment]
Thanks @thraxil. This is a one-liner fix: https://github.com/appsembler/figures/blob/master/figures/views.py#L140 . I don't think any tests exist that expect basic auth
